[project]
name = "fastCDK"
version = "1.0.0"
description = "DSL for fast generation AWS CDK code of most commonly used AWS services"
authors = [{ name = "Lazar M. Marković", email = "office@lazarmarkovic.net" }]
maintainers = [
  { name = "Lazar M. Marković", email = "office@lazarmarkovic.net" },
]
readme = "README.md"
license = { text = "MIT" }
keywords = ["DSL", "AWS CDK", "code generator"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "Topic :: Software Development :: Compilers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8, <3.13"
dependencies = [
  "lark >= 1.2.2",
  "Jinja2 >= 3.1.5",
  "importlib-metadata; python_version < '3.10'", # For entry_points backward compatibility
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.optional-dependencies]
cli = ["click >=7.0, <9.0"]
dev = ["click >=7.0, <9.0", "ruff", "mkdocs", "mike"]
test = [
  "click >=7.0, <9.0",
  "ruff",
  "attrs",
  "coverage",
  "coveralls",
  "pytest",
  "html5lib",
]


[tool.ruff]
line-length = 133
indent-width = 2

[tool.ruff.lint]
# https://docs.astral.sh/ruff/linter/#rule-selection
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
