
# AWS Configuration
AwsStackName = "FastCdkExampleAppDev"
AwsAccountId = "397130095288"
AwsRegion = "eu-west-1"

# Project Information
ProjectName = "fcdk-example"
Environment = "dev"
Version = "1.0.0"

# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end




[BuildParams]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end


[BuildParams.Root]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end

VpcCidr = "10.0.0.0/16"

[BuildParams.SimpleECSBackend]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end

AlbCertificateARN = "ALB::CERT::ARN"
AlbHealthCheckApiPath = "/api/healthCheck"
SecretARN = "SECRET:ARN"

[envConfig]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end


[envConfig.BuildParams]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end


[envConfig.BuildParams.SimpleECSBackend]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end

HostPort = "3030"

