
# AWS Configuration
AwsStackName = "FastCdkExampleAppDev"
AwsAccountId = "397130095288"
AwsRegion = "eu-west-1"

# Project Information
ProjectName = "fcdk-example"
Environment = "dev"
Version = "1.0.0"

# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end




[BuildParams]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end


[BuildParams.Root]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end

BaseDomainName1 = "some:ARN:of:AWS"
DomainName = "test.com"
GitOwner = "git-user-or-org-name"
OpenIdConnectProviderARN = "myOpenIdConnectProviderARN"
VpcCidr = "10.0.0.0/16"

[BuildParams.S3BasedCF]
# fastcdk:keep-start id=OtherYamlVars sig=v0.0.1>
# fastcdk:keep-end

CloudFrontCertificateARN = "my-cf-cert"
CloudFrontConnectionSecret = "some-secret-string"
GitRepoName = "git-repo-name"
GitRepoPullBranchName = "git-pull-branch-name"
S3BucketName = "my-frontend-bucket"

